# PersistentVolumeClaims para cada base de datos PostgreSQL.
# storageClassName: "" usa el StorageClass por defecto del clúster K3s (local-path).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-auth
  namespace: filmstars
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-localidades
  namespace: filmstars
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-funciones
  namespace: filmstars
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-reservas
  namespace: filmstars
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-pagos
  namespace: filmstars
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
