apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-reservas
  namespace: filmstars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-reservas
  template:
    metadata:
      labels:
        app: postgres-reservas
    spec:
      containers:
        - name: postgres-reservas
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: filmstars-config
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filmstars-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: reservas-service-config
                  key: DB_NAME
          volumeMounts:
            - name: postgres-reservas-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: [pg_isready, -U, postgres, -d, reservas_service]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: [pg_isready, -U, postgres, -d, reservas_service]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: postgres-reservas-data
          persistentVolumeClaim:
            claimName: pvc-postgres-reservas

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reservas
  namespace: filmstars
spec:
  selector:
    app: postgres-reservas
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
