# ──────────────────────────────────────────────────────────────────────────────
# ConfigMap global: valores estáticos compartidos entre todos los servicios.
# ${DB_SERVER_PRIVATE_IP} es sustituido por envsubst en CI/CD antes de aplicar.
# ──────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: filmstars-config
  namespace: filmstars
data:
  DB_USERNAME: "postgres"

  JWT_EXPIRES_IN: "1h"
  DEFAULT_ROLE: "CLIENTE"

  AUTH_SERVICE_URL: "http://auth-service:3001"
  LOCALIDADES_SERVICE_URL: "http://localidades-service:3002"
  FUNCIONES_SERVICE_URL: "http://funciones-service:3003"
  RESERVAS_SERVICE_URL: "http://reservas-service:3004"
  PAGOS_SERVICE_URL: "http://pagos-service:3005"
  ESCANEO_SERVICE_URL: "http://escaneo-service:3007"
  FRONTEND_URL: "http://frontend:80"

  RABBITMQ_HOST: "${DB_SERVER_PRIVATE_IP}"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  RABBITMQ_AMQP_PORT: "5672"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: filmstars
data:
  PORT: "3001"
  DB_HOST: "${DB_SERVER_PRIVATE_IP}"
  DB_PORT: "5433"
  DB_NAME: "auth_service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localidades-service-config
  namespace: filmstars
data:
  PORT: "3002"
  DB_HOST: "${DB_SERVER_PRIVATE_IP}"
  DB_PORT: "5434"
  DB_NAME: "localidades_service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: funciones-service-config
  namespace: filmstars
data:
  PORT: "3003"
  DB_HOST: "${DB_SERVER_PRIVATE_IP}"
  DB_PORT: "5435"
  DB_NAME: "funciones_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reservas-service-config
  namespace: filmstars
data:
  PORT: "3004"
  DB_HOST: "${DB_SERVER_PRIVATE_IP}"
  DB_PORT: "5436"
  DB_NAME: "reservas_service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pagos-service-config
  namespace: filmstars
data:
  PORT: "3005"
  DB_HOST: "${DB_SERVER_PRIVATE_IP}"
  DB_PORT: "5437"
  DB_NAME: "pagos_service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: escaneo-service-config
  namespace: filmstars
data:
  PORT: "3007"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: filmstars
data:
  PORT: "3006"
